[package]
name = "velari"
version = "0.4.5-beta.1"
edition = "2021"
authors = ["zyrndotio"]
description = "Velari language compiler and interpreter"
license = "Apache-2.0"
repository = "https://github.com/zyrndotio/Velari"
homepage = "https://github.com/zyrndotio/Velari"

[dependencies]

[package.metadata.packager]
product-name = "Velari"
identifier = "com.zyrndotio.velari"
icons = ["assets/velari.png"]
version = "0.4.5-beta.1"
# Tells the packager to build the optimized release binary right before bundling
before-packaging-command = "cargo build --release"

[package.metadata.packager.nsis]
compression = "lzma"
