#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Span { pub start: usize, pub end: usize, pub line: usize, pub column: usize }
#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind { BeginProgram, End, Let, Be, If, Then, Otherwise, Print, Repeat, Times, Create, Window, Title, Width, Height, True, False, Null, And, Or, Identifier(String), Number(f64), StringLiteral(String), Plus, Minus, Star, Slash, EqualEqual, LeftParen, RightParen, Newline, Eof }
#[derive(Debug, Clone, PartialEq)]
pub struct Token { pub kind: TokenKind, pub span: Span }
#[derive(Debug, Clone, PartialEq)]
pub struct LexError { pub message: String, pub span: Span }
pub struct Lexer<'a> { input: &'a str, chars: Vec<char>, pos: usize, line: usize, column: usize }
impl<'a> Lexer<'a> {
 pub fn new(input: &'a str) -> Self { Self { input, chars: input.chars().collect(), pos: 0, line: 1, column: 1 } }
 fn current(&self)->Option<char>{self.chars.get(self.pos).copied()}
 fn advance(&mut self)->Option<char>{let c=self.current()?;self.pos+=1;if c=='\n'{self.line+=1;self.column=1}else{self.column+=1}Some(c)}
 fn span(&self,s:usize,l:usize,c:usize)->Span{Span{start:s,end:self.pos,line:l,column:c}}
 fn token(&self,k:TokenKind,s:usize,l:usize,c:usize)->Token{Token{kind:k,span:self.span(s,l,c)}}
 pub fn tokenize(&mut self)->Result<Vec<Token>,Vec<LexError>>{let mut out=Vec::new();let mut errors=Vec::new();while let Some(c)=self.current(){let s=self.pos;let l=self.line;let col=self.column;if c.is_whitespace(){self.advance();continue}if c=='#'{while self.current().is_some()&&self.current()!=Some('\n'){self.advance();}continue}if c=='\n'{self.advance();out.push(self.token(TokenKind::Newline,s,l,col));continue}if c=='"'{self.advance();let mut v=String::new();let mut closed=false;while let Some(ch)=self.current(){self.advance();match ch{'"'=>{closed=true;break},'\\'=>match self.current(){Some('n')=>{self.advance();v.push('\n')},Some('t')=>{self.advance();v.push('\t')},Some('"')=>{self.advance();v.push('"')},Some('\\')=>{self.advance();v.push('\\')},_=>v.push('\\')},_=>v.push(ch)}}if closed{out.push(self.token(TokenKind::StringLiteral(v),s,l,col))}else{errors.push(LexError{message:"unterminated string literal".into(),span:self.span(s,l,col)})}continue}if c.is_ascii_digit()||(c=='.'&&self.chars.get(self.pos+1).is_some_and(|x|x.is_ascii_digit())){let mut t=String::new();let mut dots=0;while let Some(ch)=self.current(){if ch.is_ascii_digit()||ch=='.'{if ch=='.'{dots+=1}t.push(ch);self.advance();}else{break}}if dots>1{errors.push(LexError{message:"invalid number literal".into(),span:self.span(s,l,col)})}else if let Ok(n)=t.parse(){out.push(self.token(TokenKind::Number(n),s,l,col))}continue}if c.is_alphabetic()||c=='_'{let mut t=String::new();while let Some(ch)=self.current(){if ch.is_alphanumeric()||ch=='_'{t.push(ch);self.advance();}else{break}}let k=match t.as_str(){"begin"=>TokenKind::BeginProgram,"end"=>TokenKind::End,"let"=>TokenKind::Let,"be"=>TokenKind::Be,"if"=>TokenKind::If,"then"=>TokenKind::Then,"otherwise"=>TokenKind::Otherwise,"print"=>TokenKind::Print,"repeat"=>TokenKind::Repeat,"times"=>TokenKind::Times,"create"=>TokenKind::Create,"window"=>TokenKind::Window,"title"=>TokenKind::Title,"width"=>TokenKind::Width,"height"=>TokenKind::Height,"true"=>TokenKind::True,"false"=>TokenKind::False,"null"=>TokenKind::Null,"is"=>TokenKind::EqualEqual,"and"=>TokenKind::And,"or"=>TokenKind::Or,_=>TokenKind::Identifier(t)};out.push(self.token(k,s,l,col));continue}let k=match c{'+' =>Some(TokenKind::Plus),'-'=>Some(TokenKind::Minus),'*'=>Some(TokenKind::Star),'/'=>Some(TokenKind::Slash),'('=>Some(TokenKind::LeftParen),')'=>Some(TokenKind::RightParen),'=' if self.chars.get(self.pos+1)==Some(&'=')=>{self.advance();Some(TokenKind::EqualEqual)},_=>None};if let Some(k)=k{self.advance();out.push(self.token(k,s,l,col))}else{self.advance();errors.push(LexError{message:format!("unexpected character `{c}`"),span:self.span(s,l,col)})}}out.push(Token{kind:TokenKind::Eof,span:Span{start:self.input.len(),end:self.input.len(),line:self.line,column:self.column}});if errors.is_empty(){Ok(out)}else{Err(errors)}}
}
#[cfg(test)] mod tests{use super::*;#[test]fn strings_and_comments(){assert!(Lexer::new("begin\n#x\nprint \"hi\\n\"\nend").tokenize().is_ok());}}
