mod lexer;mod ast;mod parser;mod semantic;mod interpreter;mod diagnostics;
use std::{env,fs,path::{Path,PathBuf}};use lexer::Lexer;use parser::Parser;use semantic::SemanticAnalyzer;use interpreter::Interpreter;use diagnostics::Diagnostic;
fn compile(source:&str,filename:&str,run:bool)->Result<(),String>{let tokens=Lexer::new(source).tokenize().map_err(|es|es.into_iter().map(|e|Diagnostic::error("E1001",e.message,e.span).render(source,filename)).collect::<Vec<_>>().join("\n"))?;let ast=Parser::new(tokens).parse_program().map_err(|es|es.into_iter().map(|e|Diagnostic::error("E2001",e.message,e.span).render(source,filename)).collect::<Vec<_>>().join("\n"))?;let mut sem=SemanticAnalyzer::new();sem.analyze(&ast).map_err(|es|es.into_iter().map(|e|Diagnostic::error("E3001",e.message,e.span).render(source,filename)).collect::<Vec<_>>().join("\n"))?;if run{Interpreter::new().execute(&ast).map_err(|e|e.0)}else{Ok(())}}
fn manifest_from(start:&Path)->Option<PathBuf>{let mut p=if start.is_file(){start.parent()?.to_path_buf()}else{start.to_path_buf()};loop{let candidate=p.join("vela.toml");if candidate.is_file(){return Some(candidate)}if !p.pop(){return None}}}
fn manifest_entry(manifest:&Path)->Result<PathBuf,String>{let text=fs::read_to_string(manifest).map_err(|e|e.to_string())?;let entry=text.lines().find_map(|l|{let (k,v)=l.split_once('=')?;if k.trim()=="entry"{Some(v.trim().trim_matches('"').to_string())}else{None}}).unwrap_or_else(||"src/main.vr".into());Ok(manifest.parent().unwrap_or(Path::new(".")).join(entry))}
fn source_path(arg:Option<String>)->Result<PathBuf,String>{let path=arg.map(PathBuf::from).unwrap_or(env::current_dir().map_err(|e|e.to_string())?);if path.is_file(){Ok(path)}else{let m=manifest_from(&path).ok_or_else(||"could not find vela.toml; provide a .vr source file or run inside a project".to_string())?;manifest_entry(&m)}}
fn run_tests(root:&Path)->Result<(),String>{let dir=root.join("tests");if !dir.is_dir(){println!("no VelaRi tests found");return Ok(())}let mut total=0;for item in fs::read_dir(&dir).map_err(|e|e.to_string())?{let path=item.map_err(|e|e.to_string())?.path();if path.extension().and_then(|x|x.to_str())!=Some("vr"){continue}total+=1;let source=fs::read_to_string(&path).map_err(|e|e.to_string())?;compile(&source,path.to_str().unwrap_or("<test>"),true)?;}println!("{total} VelaRi test(s) passed");Ok(())}
fn usage(){eprintln!("VelaRi 0.3.2\nusage: velari <check|run|test|new|version> [file|project]");}
fn main(){let mut args=env::args().skip(1);let command=args.next();let result=match command.as_deref(){Some("version")=>{println!("velari 0.3.2");Ok(())},Some("check")|Some("run")=>{let run=command.as_deref()==Some("run");let path=source_path(args.next());path.and_then(|p|{let source=fs::read_to_string(&p).map_err(|e|e.to_string())?;compile(&source,p.to_str().unwrap_or("<source>"),run).map(|_|{if !run{println!("check succeeded")}})})},Some("test")=>{let path=args.next().map(PathBuf::from).unwrap_or_else(||env::current_dir().unwrap());let root=if path.is_file(){path.parent().unwrap_or(Path::new(".")).to_path_buf()}else{path};run_tests(&root)},Some("new")=>{let dir=args.next().unwrap_or_else(||"velari-app".into());let package_name=Path::new(&dir).file_name().and_then(|n|n.to_str()).unwrap_or("velari-app").replace(" ","-");fs::create_dir_all(Path::new(&dir).join("src")).map_err(|e|e.to_string()).and_then(|_|{fs::write(Path::new(&dir).join("src/main.vr"),"begin\n print \"hello, VelaRi\"\nend\n").map_err(|e|e.to_string())?;fs::write(Path::new(&dir).join("vela.toml"),format!("[package]\nname = \"{package_name}\"\nversion = \"0.1.0\"\nentry = \"src/main.vr\"\n")).map_err(|e|e.to_string())?;fs::create_dir_all(Path::new(&dir).join("tests")).map_err(|e|e.to_string())?;println!("created {dir}");Ok(())})},_=>{usage();Ok(())}};if let Err(e)=result{eprintln!("{e}");std::process::exit(1)}}
